name: mpg123-cm
version: 1.30.2
base: core18
summary: A fast console MPEG audio player
description: |
  mpg123 is a console-based MPEG audio decoder and player for layers
  1, 2 and 3, including MP2 and MP3, from local files or streamed from
  the network.
grade: stable
confinement: strict

parts:
  mpg123:
    after: [patches]
    plugin: autotools
    source: https://sourceforge.net/projects/mpg123/files/mpg123/1.30.2/mpg123-1.30.2.tar.bz2
    configflags:
      - --prefix=
      - --with-default-audio=pulse
      - --enable-network=yes
      - --enable-ipv6=yes
    build-packages:
      - build-essential
      - libpulse-dev
      - libasound2-dev
    stage-packages:
      - libpulse0
      - libasound2
    override-pull: |
      snapcraftctl pull
      # patch -d "$SNAPCRAFT_PART_SRC" -p1 < "$SNAPCRAFT_STAGE"/mpg123-1.28.0-armfpu-neon.diff
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -include

  patches:
    plugin: dump
    source: patches
    prime:
      - -*

apps:
  mpg123:
    command: bin/mpg123
    plugs:
      - home
      - pulseaudio
      - alsa
      - audio-playback
      - network
      - x11  # needed to use pulse
    environment:
      MPG123_MODDIR: $SNAP/lib/mpg123

  id3dump:
    command: bin/mpg123-id3dump
    plugs:
      - home

  mpg123-strip:
    command: bin/mpg123-strip
    plugs:
      - home

  out123:
    command: bin/out123
    plugs:
      - home
      - pulseaudio
      - alsa
      - audio-playback
      - network
      - x11  # needed to use pulse

layout:
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
