name: mpg123-cm
version: 1.32.3
base: core22
summary: A fast console MPEG audio player
description: |
  mpg123 is a console-based MPEG audio decoder and player for layers
  1, 2 and 3, including MP2 and MP3, from local files or streamed from
  the network.
grade: stable
confinement: strict

parts:
  mpg123:
    plugin: autotools
    source: https://sourceforge.net/projects/mpg123/files/mpg123/$SNAPCRAFT_PROJECT_VERSION/mpg123-$SNAPCRAFT_PROJECT_VERSION.tar.bz2
    autotools-configure-parameters:
      - --prefix=
      - --with-default-audio=pulse
      - --enable-network=yes
      - --enable-ipv6=yes
    build-packages:
      - build-essential
      - libpulse-dev
      - libasound2-dev
    stage-packages:
      - libpulse0
      - libasound2
    override-pull: |
      craftctl default
      # patch -d "$CRAFT_PART_SRC" -p1 < "$CRAFT_PROJECT_DIR"/patches/mpg123-1.28.0-armfpu-neon.diff
    override-build: |
      craftctl default
      cp "$CRAFT_PROJECT_DIR"/scripts/pulse-runner "$CRAFT_PART_INSTALL"
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -include

apps:
  mpg123:
    command: bin/mpg123
    command-chain: [pulse-runner]
    plugs:
      - home
      - pulseaudio
      - alsa
      - audio-playback
      - network
      - removable-media
      - x11  # needed to use pulse
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
      MPG123_MODDIR: $SNAP/lib/mpg123

  id3dump:
    command: bin/mpg123-id3dump
    plugs:
      - home

  mpg123-strip:
    command: bin/mpg123-strip
    plugs:
      - home

  out123:
    command: bin/out123
    command-chain: [pulse-runner]
    plugs:
      - home
      - pulseaudio
      - alsa
      - audio-playback
      - network
      - removable-media
      - x11  # needed to use pulse

layout:
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
